### PR TITLE
Add solution to problem 22

### PR DESCRIPTION
**Pull request by damiecode**
Add solution to the problem 22.

### CODE REVIEW

**Comment by satyajitghana** [comment]
Hi, thanks for your contribution !

can you add names.txt to this PR ?

**Comment by damiecode** [comment]
okay I will

**Comment by damiecode** [comment]
What names should be in the file?

**Comment by satyajitghana** [comment]
> What names should be in the file?

this one https://projecteuler.net/project/resources/p022_names.txt , and add a link to this file in README.txt
 
also add the output of the program in README.md

**Comment by damiecode** [comment]
I have added the file and output

**Comment by satyajitghana** [comment]
Looks Good, Thanks for your contribution !

**Pull request merged**
